### ISSUE TITLE
Validation errors should not shift input fields

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#232]
**Describe the bug**
When error messages appear below input fields, everything below them shifts.

**Expected behavior**
The layout of the form should remain static when validation errors are present.

**Comment by daviddkkim** [comment]
![Screen Shot 2021-04-22 at 11 15 39 AM](https://user-images.githubusercontent.com/12561526/115739627-15068680-a35c-11eb-86e1-ca0b87644ebe.png)

I can make this work for if there is only error message. but if there are both error message And help message, I'm not sure I can make the spacing work because of how absolute positioning works with css. But I could be completely wrong here. 

options:
1. I can make it so that when error message is present, we hide the help message. 
2. We figure out some genius way to absolute position both the help and error message relative to each other despite both being absolute positions

**Comment by daviddkkim** [comment]
I took a look at how other design systems handle this,

[Material UI](https://material-ui.com/components/text-fields/#form-props) has it so that the helper text does both normal state helper message and error message. The error state toggle just changes the color and messaging of the helper text. 

[Carbon](https://react.carbondesignsystem.com/?path=/story/components-form--default) has it so that the error message take up space when it appears.

**Comment by mavarius** [comment]
Let's go with the error message replacing the helper text.

**Comment by kristinarobinson** [comment]
close this until a specific input field is referenced.
