### ISSUE TITLE
Split Navigation into Account Navigation and Application Navigation

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#383]
**Is your feature request related to a problem? Please describe.**
Users are unable to find the upgrade button or their account settings in the application.

**Describe the solution you'd like**
- Add a top-level navigation bar that houses the account navigation
- Add an ever-present Upgrade button to the top-level navigation bar
- Add a logo to the top-level navigation that acts as a home button
- Remove the logo and cloud from the application navigation bar.

**Describe alternatives you've considered**
- Adding an upgrade button below the existing navigation bar
- Adding the current subscription level next to the org name subtitle with a popover upgrade option
- Adding an ever-present upgrade button next to the org name

**Additional context**
![image.png](https://images.zenhubusercontent.com/5cffe8c638b9052bc7e6b150/f6694cc4-f2d3-4e5e-b1ca-e1222f25dd5b)

**Comment by alexpaxton** [comment]
I think there's potential to break this down into a handful of components:

- Avatar circle thing
- Combination of avatar and dropdown menu or popover 
- Top navigation with child pass through
  - Not sure what I would call this thing, but it is a different form of navigation that could hypothetically be used for something else than "account"

**Comment by mnorriswalker** [comment]
1. I'd also add the Figma link here for the reference purposes of others:
https://www.figma.com/proto/lxjjwlh1oftKYCMVs6tnVL/Cloud-2-Navigation-Options?node-id=13%3A53&viewport=660%2C-197%2C0.25&scaling=contain

2. A/B Test

We want to A/B Test the text of the Upgrade Call-to-Action Button. In order to do that we need to add an Optimize code snippet to the Cloud App.

Variant A: Upgrade My Plan
Variant B: Go Unlimited

![image](https://user-images.githubusercontent.com/56005508/68612021-64ab0800-0470-11ea-99d6-9077d6c73880.png)


```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-45024174-18"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-45024174-18', { 'optimize_id': 'GTM-TML255J'});
</script>
```

**Comment by mnorriswalker** [comment]
@mavarius shall we also update the Feedback in the navigation to link to the feedback sessions: https://calendly.com/influxdata-research/cloud
